name: Reusable CI (build & test)

on:
  workflow_call:
    inputs:
      node_versions:
        description: 'Node versions (JSON array)'
        required: false
        type: string
        default: '["18.x","20.x"]'
      schemas:
        description: 'Schema matrix (JSON array)'
        required: false
        type: string
        default: '["v1"]'
      allow_v2_failure:
        description: 'Treat SCHEMA=v2 as non-blocking'
        required: false
        type: boolean
        default: true
      working_directory:
        description: 'Working directory for install/build/test'
        required: false
        type: string
        default: '.'

jobs:
  build-and-test:
    name: Node ${{ matrix.node }} / Schema ${{ matrix.schema }}
    runs-on: ubuntu-latest
    continue-on-error: ${{ inputs.allow_v2_failure && matrix.schema == 'v2' }}
    env:
      SCHEMA: ${{ matrix.schema }}
    strategy:
      fail-fast: false
      matrix:
        node: ${{ fromJson(inputs.node_versions) }}
        schema: ${{ fromJson(inputs.schemas) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Enable Corepack
        run: corepack enable

      - name: Prepare pnpm from packageManager
        run: |
          PACKAGE_JSON="${{ inputs.working_directory }}/package.json"
          if [ -f "$PACKAGE_JSON" ]; then
            PACKAGE_MANAGER=$(node -p "require('./$PACKAGE_JSON').packageManager ?? ''")
            if [ -n "$PACKAGE_MANAGER" ]; then
              corepack prepare "$PACKAGE_MANAGER" --activate
            else
              echo "packageManager is not defined; skipping pnpm activation."
            fi
          else
            echo "package.json not found at $PACKAGE_JSON; skipping pnpm activation."
          fi

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: pnpm-store-${{ runner.os }}-${{ hashFiles(format('{0}/pnpm-lock.yaml', inputs.working_directory)) }}
          restore-keys: |
            pnpm-store-${{ runner.os }}-

      - name: Install dependencies
        working-directory: ${{ inputs.working_directory }}
        run: pnpm install --frozen-lockfile

      - name: Build
        working-directory: ${{ inputs.working_directory }}
        run: pnpm -w run build

      - name: Test
        working-directory: ${{ inputs.working_directory }}
        run: pnpm -w run test

      - name: Soft-fail note for schema v2
        if: ${{ inputs.allow_v2_failure && matrix.schema == 'v2' }}
        run: echo 'SCHEMA=v2 run is marked as non-blocking (allowed failure).'
