name: CI

on:
  pull_request:
  push:

jobs:
  main:
    uses: ./.github/workflows/ci-reusable.yml
    with:
      node_versions: '["18.x","20.x"]'
      schemas: '["v1","v2"]'
      allow_v2_failure: true
      working_directory: '.'
